### ISSUE TITLE
Issue on server - Version 1.1.3 for MC 1.11.2

### ISSUE THREAD

**Issue by ghetta82** [tyra314/ToolProgression#4]
This is the crashlog on launch server.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.223-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.7.0.268-universal.jar)
  FarseekCoreMod (Farseek-1.11-2.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  LoadingPlugin (HardcoreDarkness-MC1.11.2-1.9.jar)
  LoadingPlugin (Skillable-beta-5.jar)
  LoadingPlugin (Quark-r1.2-92.jar)
  TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 6/11/17 7:03 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tool Progression (toolprogression)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at exterminatorjeff.undergroundbiomes.common.block.wall.UBStoneWall.func_149732_F(UBStoneWall.java:79)
	at tyra314.toolprogression.harvest.OverwriteHelper.handleBlock(OverwriteHelper.java:18)
	at tyra314.toolprogression.proxy.CommonProxy.postInit(CommonProxy.java:100)
	at tyra314.toolprogression.ToolProgressionMod.postInit(ToolProgressionMod.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:109)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:215)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 124964632 bytes (119 MB) / 516268032 bytes (492 MB) up to 4233953280 bytes (4037 MB)
	JVM Flags: 6 total; -Xmx4096M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=7 -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2315 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2315-universal.jar) 
	UCHIJ	forge{13.20.0.2315} [Minecraft Forge] (forge-1.11.2-13.20.0.2315-universal.jar) 
	UCHIJ	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.7.0.268-universal.jar) 
	UCHIJ	animalium{0.2.0} [animalium] (Animalium-0.2.0.jar) 
	UCHIJ	animania{1.1.4} [Animania] (animania-1.11.2-1.1.4.jar) 
	UCHIJ	jei{4.5.0.287} [Just Enough Items] (jei_1.11.2-4.5.0.287.jar) 
	UCHIJ	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJ	aquaculture{1.5.0} [Aquaculture] (Aquaculture-1.11.2-1.5.0.33.jar) 
	UCHIJ	immcraft{1.3.3} [Immersive Craft] (immcraft-1.1x-1.3.3.jar) 
	UCHIJ	aquamunda{0.1.1beta} [Aqua Munda] (aquamunda-0.1.1beta.jar) 
	UCHIJ	quark{r1.2-92} [Quark] (Quark-r1.2-92.jar) 
	UCHIJ	skillable{beta-5} [Skillable] (Skillable-beta-5.jar) 
	UCHIJ	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJ	buildcraftlib{7.99.4} [BuildCraft Lib] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcraftcore{7.99.4} [BuildCraft] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcraftfactory{7.99.4} [BC Factory] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcrafttransport{7.99.4} [BC Transport] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcraftbuilders{7.99.4} [BC Builders] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcraftenergy{7.99.4} [BC Energy] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcraftrobotics{7.99.4} [BC Robotics] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcraftsilicon{7.99.4} [BC Silicon] (buildcraft-7.99.4.jar) 
	UCHIJ	cavern{1.7.9} [Cavern] (Cavern_1.11.2-v1.7.9.jar) 
	UCHIJ	caverntweaks{1.0b} [Cavern Tweaks] (caverntweaks-1.11.2-1.0b.jar) 
	UCHIJ	ceramics{1.11.2-1.2.1b} [Ceramics] (Ceramics-1.11.2-1.2.1b.jar) 
	UCHIJ	chegen{1.0.1} [Chest Generator] (chegen-1.11.2-1.0.1.jar) 
	UCHIJ	codechickenlib{2.7.0.268} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.7.0.268-universal.jar) 
	UCHIJ	cyclopscore{0.10.4} [Cyclops Core] (CyclopsCore-1.11.2-0.10.4.jar) 
	UCHIJ	colossalchests{1.6.1} [Colossal Chests] (ColossalChests-1.11.2-1.6.1.jar) 
	UCHIJ	craftingtweaks{7.1.9} [Crafting Tweaks] (CraftingTweaks_1.11.2-7.1.9.jar) 
	UCHIJ	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.11.2-3.0.25.jar) 
	UCHIJ	crafttweaker{3.0.25} [Crafttweaker] (CraftTweaker-1.11.2-3.0.25.jar) 
	UCHIJ	customstuff3{0.10.23} [Custom Stuff 3] (CustomStuff3-1.11.2-0.10.23.jar) 
	UCHIJ	earthworks{1.3.2} [Earthworks] (Earthworks-1.11.2-1.3.2.jar) 
	UCHIJ	farseek{2.1} [Farseek] (Farseek-1.11-2.1.jar) 
	UCHIJ	nei{${mod_version}} [Not Enough Items] (NotEnoughItems-1.11.2-2.3.0.223-universal.jar) 
	UCHIJ	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5.jar) 
	UCHIJ	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.5.jar) 
	UCHIJ	hardcoredarkness{1.9} [Hardcore Darkness] (HardcoreDarkness-MC1.11.2-1.9.jar) 
	UCHIJ	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
	UCHIJ	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJ	jaff{1.6_for_1.11.2} [Just a Few Fish] (JustAFewFish-1.6_for_1.11.2.jar) 
	UCHIJ	loottweaker{0.0.6.2} [LootTweaker] (LootTweaker-1.11.2-0.0.6.2.jar) 
	UCHIJ	minecolonies{1.11.2-0.8.1784} [MineColonies] (minecolonies-universal-1.11.2-0.8.1784.jar) 
	UCHIJ	mtrm{1.2.1.23} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.11.2-1.2.1.23.jar) 
	UCHIJ	mobtotems{1.11.2-0.3.0} [Mob Totems] (mobtotems-1.11.2-0.3.0.jar) 
	UCHIJ	morpheus{1.11.2-3.2.14} [Morpheus] (Morpheus-1.11.2-3.2.14.jar) 
	UCHIJ	nutrition{1.2.0} [Nutrition] (Nutrition-1.11.2-1.2.0.jar) 
	UCHIJ	oreexcavation{1.3.95} [OreExcavation] (OreExcavation-1.3.95.jar) 
	UCHIJ	p455w0rdslib{1.0.15} [p455w0rd's Library] (p455w0rdslib-1.11.2-1.0.15.jar) 
	UCHIJ	placeableitems{3.0.4.1} [Placeable Items Mod] (placeableitems-3.0.4.1.jar) 
	UCHIJ	survivalist{1.10.1} [Survivalist] (Survivalist-1.11.2-1.10.1.jar) 
	UCHIJ	primal{0.4.1} [PrimalCore] (PrimalCore-0.4.1.jar) 
	UCHIJ	realdrops{1.1.10} [Realistic Item Drops] (RealisticItemDrops-1.1.10.jar) 
	UCHIJ	roots{0.018} [Roots 2] (roots-2-0.018.jar) 
	UCHIJ	rustic{0.3.5} [Rustic] (rustic-0.3.5.jar) 
	UCHIJ	streams{0.3} [Streams] (Streams-1.11-0.3.jar) 
	UCHIJ	toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.5.jar) 
	UCHIJ	tanspit{@VERSION@} [Campfire Spit] (tanspit-1.11.2-1.3.jar) 
	UCHIJ	theoneprobe{1.4.7} [The One Probe] (theoneprobe-1.1x-1.4.7.jar) 
	UCHIE	toolprogression{1.0} [Tool Progression] (toolprogression-1.11.2-1.1.3.jar) 
	UCHIJ	tanaddons{3.0.8} [Tough Expansion] (ToughExpansion-1.11.2-3.0.8.jar) 
	UCHIJ	undergroundbiomes{1.0.v.18} [Underground Biomes] (UndergroundBiomesConstructs-1.11-1.0.v.19.jar) 
	UCHIJ	wanionlib{1.11.2-1.0} [WanionLib] (WanionLib-1.11.2-1.0.jar) 
	UCHIJ	wearablebackpacks{2.4.1} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.4.1.jar) 
	UCHIJ	wolfarmor{1.3.2} [Wolf Armor and Storage] (wolfarmor-1.3.3.6.jar) 
	UCHIJ	wopper{1.11.2-r3} [Wopper] (Wopper-1.11.2-r3.jar) 
	UCHIJ	unidict{1.11.2-1.0} [UniDict] (UniDict-1.11.2-1.0.jar) 
	Loaded coremods (and transformers): 
NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.223-universal.jar)
  codechicken.nei.asm.NEITransformer
CCLCorePlugin (CodeChickenLib-1.11.2-2.7.0.268-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
FarseekCoreMod (Farseek-1.11-2.1.jar)
  farseek.core.FarseekClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (HardcoreDarkness-MC1.11.2-1.9.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
LoadingPlugin (Skillable-beta-5.jar)
  vazkii.skillable.base.asm.ClassTransformer
LoadingPlugin (Quark-r1.2-92.jar)
  vazkii.quark.base.asm.ClassTransformer
TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	nei Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by tyra314** [comment]
I'm not sure, who is to blame here. Might as well be an issue in Underground Biomes.

**Comment by tyra314** [comment]
Fixed in version 1.1.4 and 1.2.1, respectively.
